# Generated by Django 5.1.2 on 2024-10-24 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_category', models.CharField(help_text='Category of the ingredient (e.g., Fruit, Meat, Vegetables, Grains)', max_length=100)),
                ('allergen_type', models.CharField(blank=True, help_text='Type of allergen, if applicable (e.g., Nuts, Dairy, Gluten)', max_length=100, null=True)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_vegan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack'), ('DR', 'Drink')], default='D', max_length=2)),
                ('preparation_time', models.IntegerField(help_text='Time in minutes')),
                ('cooking_time', models.IntegerField(help_text='Time in minutes')),
                ('instructions', models.TextField()),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_vegan', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the recipe (e.g., High Protein, Gluten-Free)', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('min_age_months', models.IntegerField(default=6, help_text='Minimum age in months for this recipe')),
                ('max_age_months', models.IntegerField(default=24, help_text='Maximum age in months for this recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='base.RecipeIngredient', to='base.ingredient'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='base.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('allergies', models.CharField(blank=True, help_text='List known allergens for the child (e.g., Nuts, Dairy)', max_length=255)),
                ('dislikes_ingredients', models.ManyToManyField(blank=True, related_name='disliked_by_children', to='base.ingredient')),
                ('likes_ingredients', models.ManyToManyField(blank=True, related_name='liked_by_children', to='base.ingredient')),
                ('dislikes_recipes', models.ManyToManyField(blank=True, related_name='disliked_by_children', to='base.recipe')),
                ('likes_recipes', models.ManyToManyField(blank=True, related_name='liked_by_children', to='base.recipe')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.userprofile')),
            ],
        ),
    ]
