# Generated by Django 5.1.2 on 2025-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ingredient_id_alter_recipe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, help_text='Tottable tips for this recipe', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_types',
            field=models.ManyToManyField(to='base.mealtype'),
        ),
    ]
