# Generated by Django 5.1.2 on 2025-01-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_recipeingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the meal plan week')),
                ('end_date', models.DateField(help_text='End date of the meal plan week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(help_text='The child this meal plan is for', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='base.child')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text='Day of the week (e.g., Monday)', max_length=10)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Side', 'Side'), ('Dessert', 'Dessert')], help_text='Type of meal', max_length=20)),
                ('custom_notes', models.TextField(blank=True, help_text='Optional notes for this meal', null=True)),
                ('recipe', models.ForeignKey(blank=True, help_text='Recipe assigned to this meal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.recipe')),
                ('meal_plan', models.ForeignKey(help_text='The meal plan this meal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='base.mealplan')),
            ],
        ),
    ]
