# Generated by Django 5.1.2 on 2025-01-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mealplan_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='custom_notes',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.AddField(
            model_name='meal',
            name='breakfast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_breakfast', to='base.recipe'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_dinner', to='base.recipe'),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_lunch', to='base.recipe'),
        ),
        migrations.AddField(
            model_name='meal',
            name='snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_snack', to='base.recipe'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
    ]
