# Generated by Django 5.1.2 on 2025-01-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_meal_custom_notes_remove_meal_meal_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_plan',
            field=models.ForeignKey(help_text='The meal plan this meal is part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='base.mealplan'),
        ),
    ]
