# Generated by Django 5.1.2 on 2025-01-15 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_meal_meal_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_variety_breakfast', models.CharField(choices=[('low', 'Low Variety'), ('medium', 'Medium Variety'), ('high', 'High Variety')], default='medium', max_length=10)),
                ('meal_variety_lunch', models.CharField(choices=[('low', 'Low Variety'), ('medium', 'Medium Variety'), ('high', 'High Variety')], default='medium', max_length=10)),
                ('meal_variety_dinner', models.CharField(choices=[('low', 'Low Variety'), ('medium', 'Medium Variety'), ('high', 'High Variety')], default='medium', max_length=10)),
                ('meal_variety_snack', models.CharField(choices=[('low', 'Low Variety'), ('medium', 'Medium Variety'), ('high', 'High Variety')], default='medium', max_length=10)),
                ('favorite_recipe_frequency', models.CharField(choices=[('very_frequent', 'Very Frequently'), ('frequent', 'Frequently'), ('rare', 'Rarely')], default='frequent', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
