# Generated by Django 5.1.2 on 2025-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_variety_breakfast',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_variety_dinner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_variety_lunch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_variety_snack',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_variety',
            field=models.JSONField(default=dict, help_text='Meal variety preferences for each meal type (e.g., breakfast, lunch).'),
        ),
    ]
