# Generated by Django 5.1.2 on 2025-01-16 19:31

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_userprofile_meal_variety_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='meal_variety',
            field=models.JSONField(default=base.models.default_meal_variety, help_text='Meal variety preferences for each meal type (e.g., breakfast, lunch).'),
        ),
    ]
