# Generated by Django 5.1.2 on 2025-01-27 10:38

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_userprofile_meal_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_recipe_frequency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_variety',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='across_week_preferences',
            field=models.JSONField(default=base.models.default_across_week_preferences, help_text='Meal variety preferences across weeks.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='within_week_preferences',
            field=models.JSONField(default=base.models.default_within_week_preferences, help_text='Meal variety preferences within a week for each meal type.'),
        ),
    ]
