# Generated by Django 5.1.2 on 2025-01-27 18:40

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_userprofile_favorite_recipe_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='across_week_preferences',
            field=models.JSONField(default=base.models.default_across_week_preferences, help_text='Meal variety preferences across weeks for each meal type.'),
        ),
    ]
