# Generated by Django 5.1.2 on 2025-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_userprofile_across_week_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(default='trialing', help_text='Stripe subscription status (e.g. trialing, active, canceled)', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
