# Generated by Django 5.1.2 on 2025-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_userprofile_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_puree',
            field=models.BooleanField(default=False, help_text='Indicates whether this recipe is a puree.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exclude_purees',
            field=models.BooleanField(default=False, help_text='Exclude puree recipes from meal plans.'),
        ),
    ]
