# Generated by Django 5.1.2 on 2025-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_recipe_is_puree_userprofile_exclude_purees'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSignupSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('provider', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_checkout_session_id', models.CharField(max_length=255)),
            ],
        ),
    ]
